### ISSUE TITLE
UI issues in saving trips

### ISSUE THREAD

**Issue by obul-reddy610** [harshitptl21/CS253#24]
**Issue Summary:**
You entered a large number in the “Spots in Your Car” field (probably beyond the valid range).

Then you entered a valid-looking smaller number (4).

It still shows the error “Not within valid range.” but also shows “Trip saved!” — which is contradictory.

**Likely Problem:**
The validation logic or UI state is not updating correctly after the invalid input is replaced with a valid one.

**Possible Root Causes:**
Stale validation state: The error message ("Not within valid range.") wasn't cleared after updating the input.

Frontend bug: The trip-saving logic is probably running even though there’s still a validation error visible.

Race condition or asynchronous validation where the component doesn’t re-check the field before submission.

"Trip saved!" is showing based on a previous valid state, even though the form now contains a validation error.

**Suggestions for Fix:**
Ensure that form validation is re-triggered on any change to the “Spots in Your Car” input.

Only allow "Trip saved!" to be displayed if all validations pass at the time of form submission.

Consider disabling the Save button until all inputs are valid.

Add console logs or debugging points to confirm when validation is triggered and what values are being checked.

![Image](https://github.com/user-attachments/assets/50522c9d-f689-4fcd-b7d6-f606c215f23c)

It is provided in the User Manual and SRS document about interactive UI but not implementing.

**Comment by harshitptl21** [comment]
Resolved.

**Comment by Swi-ft** [comment]
I have filled in the details but with 59 riders

![Image](https://github.com/user-attachments/assets/85dd861a-12b9-402f-bc63-2ed097eb4819)

I have then clicked on "Share"

![Image](https://github.com/user-attachments/assets/25a3c8aa-1bba-4b18-bf00-95da9c228352)

I have then changed it to 4 (the issue you mentioned is resolved isn't resolved yet)

![Image](https://github.com/user-attachments/assets/ba507d9e-9ab2-4a65-ad77-7ecde5170742)

I have then clicked on "Share"

![Image](https://github.com/user-attachments/assets/8ebdd918-59b6-4e32-bbbb-fbd4db3dc5c4)

Not only is it showing an error, I have no idea what the error is and why it is occurring, this is why we have asked for you to add messages, like in the case of #12 but well you guys have decided not to act on it. This is the reason why we asked for pop-up messages or notifs in the 1st place

**Comment by harshitptl21** [comment]
Check console.

**Comment by Swi-ft** [comment]
No. We'll be waiting for the actual response to the issue raised.

**Comment by harshitptl21** [comment]
I'm not encountering the issue myself, so please check the console and report any error messages.

**Comment by Swi-ft** [comment]
"I have then changed it to 4 (the issue you mentioned is resolved isn't resolved yet)" And this?
